spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      sms:
        host: http://home.whycools.com
        path: /platapi/aliSms/sendSms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5


  application:
    name: gulimall-third-party

server:
  port: 30000