server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.9.111:8848

    sentinel:
      transport:
        dashboard: 192.168.9.111:8080

  redis:
    host: 192.168.9.111
    port: 6379

feign:
  sentinel:
    enabled: true

  thymeleaf:
    cache: false

  session:
    store-type: redis

logging:
  level:
    com.xunqi.gulimall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: '*'
