server:
  port: 40000


spring:
  elasticsearch:
    rest:
      uris: http://192.168.9.111:9200
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.9.111:8848

    sentinel:
      transport:
        dashboard: 192.168.9.111:8080

  redis:
    port: 6379
    host: 192.168.9.111

feign:
  sentinel:
    enabled: true


  session:
    store-type: redis

gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'


